import Clipboard from '@react-native-clipboard/clipboard';
import {useAppState} from '@react-native-community/hooks';
import {AxiosResponse} from 'axios';
import Translator from 'bazinga-translator';
import _ from 'lodash';
import React, {useCallback, useEffect, useState} from 'react';
import {Alert, Text, View} from 'react-native';

import {SubmitButton} from '../../../components/form';
import KeyboardAvoidingView from '../../../components/form/keyboardAvoidingView';
import KeycodeInput from '../../../components/keycodeInput';
import {isAndroid, isIOS} from '../../../helpers/device';
import API from '../../../services/api';
import {Colors, DarkColors} from '../../../styles';
import {useDark} from '../../../theme';
import {ProfileStackScreenFunctionalComponent} from '../../../types/navigation';
import {TOTPButtonColor, TOTPButtonDarkColor} from './index';
import styles from './styles';

type TOTPCodeResponse = Partial<{
    success: boolean;
    recovery: string;
    error: string;
}>;

const TOTPSetupCodeScreen: ProfileStackScreenFunctionalComponent<'TOTPSetupCode'> = ({navigation, route}) => {
    const currentAppState = useAppState();
    const isDark = useDark();
    const [secret] = useState<string>(route.params.secret);
    const [code, setCode] = useState('');
    const [disabled, setDisabled] = useState(true);
    const [loader, setLoader] = useState(false);

    const onChange = useCallback((userCode) => {
        setCode(userCode);
    }, []);

    const onComplete = useCallback(() => {
        setDisabled(false);
    }, []);

    const checkClipboard = useCallback(async () => {
        const oneTimeCode = await Clipboard.getString();

        if (_.isString(oneTimeCode)) {
            const code = oneTimeCode.replace(/[^0-9]/, '');

            if (code === oneTimeCode.replace(' ', '') && code.length === 6) {
                setCode(code);
                onComplete();
            }
        }
    }, [onComplete]);

    const openCompleteSetup = useCallback(async () => {
        if (_.isString(secret)) {
            setLoader(true);
            let response: AxiosResponse<TOTPCodeResponse> | null = null;

            try {
                response = await API.post<TOTPCodeResponse>('/profile/2factor/init', {secret, code});
            } finally {
                setLoader(false);
            }

            if (_.isObject(response)) {
                const {data} = response;

                if (_.isObject(data)) {
                    const {error, success, recovery} = data;

                    if (error) {
                        Alert.alert(
                            '',
                            error,
                            [
                                {
                                    text: Translator.trans('button.ok', {}, 'messages'),
                                },
                            ],
                            {cancelable: false},
                        );
                        setDisabled(true);
                        setCode('');
                    }

                    if (success && recovery) {
                        navigation.navigate('TOTPCompleteSetup', {recovery});
                    }
                }
            }
        }
    }, [code, navigation, secret]);

    useEffect(() => {
        if (code.length < 6) {
            setDisabled(true);
        }
    }, [code]);

    useEffect(() => {
        if (currentAppState === 'active') {
            checkClipboard();
        }
    }, [checkClipboard, currentAppState, navigation]);

    const render = useCallback(
        () => (
            <View style={[styles.page, isDark && styles.pageDark]}>
                <Text style={[styles.container, styles.text, styles.textTitle, isDark && styles.textDark]}>
                    {Translator.trans(/** @Desc("Enter Code") */ 'two-factor.enter-code', {}, 'mobile-native')}
                </Text>
                <Text style={[styles.container, styles.text, isDark && styles.textDark]}>
                    {Translator.trans(
                        /** @Desc("Enter the 6-digit login code generated by your authentication app") */ 'two-factor.login-code',
                        {},
                        'mobile-native',
                    )}
                </Text>
                <View style={styles.container}>
                    <KeycodeInput
                        alphaNumeric={false}
                        value={code}
                        onChange={onChange}
                        onComplete={onComplete}
                        type='line'
                        colorText={isAndroid && isDark ? DarkColors.gold : Colors.gold}
                    />
                </View>
                <View style={styles.footer}>
                    <SubmitButton
                        label={Translator.trans('form.button.next', {}, 'messages')}
                        disabled={disabled}
                        loader={loader}
                        onPress={openCompleteSetup}
                        color={isDark ? TOTPButtonDarkColor : TOTPButtonColor}
                    />
                </View>
            </View>
        ),
        [code, disabled, isDark, loader, onChange, onComplete, openCompleteSetup],
    );

    return isIOS ? <KeyboardAvoidingView>{render()}</KeyboardAvoidingView> : render();
};

TOTPSetupCodeScreen.navigationOptions = () => ({
    title: Translator.trans(/** @Desc("Confirmation Code") */ 'two-factor.confirmation-code', {}, 'mobile-native'),
    headerBackTitle: Translator.trans('buttons.back', {}, 'mobile'),
});

export default TOTPSetupCodeScreen;
