import {StyleSheet} from 'react-native';

import {Colors, DarkColors, Fonts} from '../../../../styles';

export default StyleSheet.create({
    badge: {
        backgroundColor: Colors.green,
        borderRadius: 2,
        padding: 2,
    },
    textBadge: {
        fontSize: 11,
        fontFamily: Fonts.regular,
        color: Colors.white,
    },
    textDark: {
        color: Colors.white,
    },
    emailSuccess: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'center',
        padding: 15,
    },
    emailSuccessText: {
        fontSize: 13,
        marginLeft: 8,
        fontFamily: Fonts.regular,
        color: '#00a67c',
    },
    emailSuccessIcon: {
        marginTop: 5,
    },
    emailWarning: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: Colors.orange,
        paddingVertical: 8,
        paddingHorizontal: 15,
    },
    emailWarningCol: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
    },
    emailWarningText: {
        fontSize: 12,
        color: Colors.white,
        fontFamily: Fonts.regular,
    },
    emailWarningDetails: {
        flex: 1,
        flexDirection: 'column',
        flexWrap: 'nowrap',
        paddingHorizontal: 15,
    },
    title: {
        flex: 1,
        flexDirection: 'column',
        flexWrap: 'nowrap',
        paddingVertical: 10,
        paddingHorizontal: 15,
        marginTop: 20,
        borderBottomColor: '#bec2cc',
        borderBottomWidth: 2,
    },
    titleDark: {
        borderBottomColor: DarkColors.border,
        borderBottomWidth: 1,
    },
    titleText: {
        fontSize: 25,
        color: Colors.grayDark,
        fontFamily: Fonts.regular,
    },
    firstRow: {
        borderTopColor: Colors.gray,
        borderTopWidth: 1,
    },
    bgLight: {
        backgroundColor: Colors.white,
    },
    bgDark: {
        backgroundColor: DarkColors.bg,
    },
    container: {
        minHeight: 52,
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderBottomColor: Colors.gray,
        borderBottomWidth: 1,
    },
    containerDark: {
        backgroundColor: DarkColors.bg,
        borderBottomColor: DarkColors.border,
    },
    containerWrap: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 10,
        paddingHorizontal: 15,
    },
    containerGrayWrap: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    containerGray: {
        // empty
    },
    caption: {
        fontSize: 15,
        fontFamily: Fonts.regular,
        color: Colors.textGray,
    },
    containerCaption: {
        flexDirection: 'column',
        flexWrap: 'nowrap',
        justifyContent: 'center',
        paddingRight: 10,
        maxWidth: '80%',
    },
    boldText: {
        fontSize: 15,
        fontFamily: Fonts.bold,
        color: Colors.textGray,
        fontWeight: 'bold',
    },
    smallText: {
        fontSize: 12,
        fontFamily: Fonts.regular,
        color: '#a1a7b3',
    },
    containerDetails: {
        flex: 1,
        flexWrap: 'nowrap',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
    arrow: {
        marginLeft: 10,
        marginRight: -5,
    },
    label: {
        marginTop: 24,
        marginBottom: 5,
        paddingHorizontal: 16,
    },
    labelText: {
        fontFamily: Fonts.regular,
        color: Colors.grayDark,
        fontSize: 12,
    },
    labelTextDark: {
        color: Colors.white,
    },
    silver: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        paddingTop: 2,
        position: 'relative',
        borderBottomWidth: 1,
        borderBottomColor: Colors.gray,
    },
    silverDark: {
        paddingTop: 0,
        borderBottomColor: DarkColors.border,
    },
    silverArrowLight: {
        position: 'absolute',
        left: 12,
        bottom: -8,
        width: 0,
        height: 0,
        borderLeftColor: 'transparent',
        borderLeftWidth: 7,
        borderTopWidth: 7,
        borderTopColor: Colors.gray,
        borderRightWidth: 7,
        borderRightColor: 'transparent',
    },
    silverArrowOutterDark: {
        opacity: 0,
        borderTopColor: Colors.black,
    },
    silverArrow: {
        position: 'absolute',
        left: 12,
        bottom: -7,
        width: 0,
        height: 0,
        borderLeftColor: 'transparent',
        borderLeftWidth: 7,
        borderTopWidth: 7,
        borderTopColor: Colors.grayLight,
        borderRightWidth: 7,
        borderRightColor: 'transparent',
    },
    silverArrowDark: {
        opacity: 0,
        borderTopColor: Colors.black,
    },
    silverItem: {
        paddingHorizontal: 15,
        height: 38,
        backgroundColor: Colors.grayLight,
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        alignItems: 'center',
    },
    silverItemDark: {
        backgroundColor: Colors.black,
    },
    silverText: {
        fontSize: 15,
        fontFamily: Fonts.regular,
        color: '#8e9199',
    },
    tableRow: {
        flex: 1,
        minHeight: 52,
        flexDirection: 'row',
        paddingVertical: 2,
        justifyContent: 'space-between',
        flexWrap: 'nowrap',
        alignItems: 'flex-start',
        paddingHorizontal: 16,
    },
    columnCaption: {
        maxWidth: '65%',
        flexDirection: 'column',
        flexWrap: 'nowrap',
        justifyContent: 'center',
        paddingRight: 10,
    },
    columnValue: {
        flex: 1,
        maxWidth: '65%',
        flexWrap: 'nowrap',
        flexDirection: 'column',
        alignItems: 'flex-end',
    },
    separator: {
        height: 1,
        backgroundColor: Colors.gray,
        marginLeft: 16,
    },
    separatorDark: {
        backgroundColor: DarkColors.border,
    },
    warningLinkContainer: {
        backgroundColor: Colors.orange,
        padding: 16,
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    warningLinkCol: {
        flex: 1,
        flexDirection: 'row',
        flexWrap: 'nowrap',
    },
    warningLinkText: {
        color: Colors.white,
        fontSize: 16,
        fontFamily: Fonts.regular,
    },
    containerDetailsRow: {
        flexWrap: 'nowrap',
        flexDirection: 'column',
        alignItems: 'flex-end',
        justifyContent: 'center',
    },
});
