# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 8",
  "iPhone 8 Plus",
  "iPhone SE",
  "iPhone X",
  "iPhone Xs Max",
  "iPad Pro (12.9-inch) (2nd generation)",
  "iPad Pro (9.7-inch)",
  "iPad Pro (12.9-inch) (3rd generation)",
  "iPad Pro (11-inch)"
])

languages([
"zh_TW",
# "ru",
# "de",
# "es",
# "pt",
# "fr",
# "zh-Hans",
# "zh-Hant"
  # "it-IT",
  # ["pt", "pt_BR"] # Portuguese with Brazilian locale
])

# The name of the scheme which contains the UI Tests
# scheme("SchemeName")

# Where should the resulting screenshots be stored?
# output_directory("./screenshots")

# remove the '#' to clear all previously generated screenshots before creating new ones
clear_previous_screenshots(true)

stop_after_first_error(true)
number_of_retries(0)
#erase_simulator(true)
reinstall_app(true)
scheme("AwardWallet")
#derived_data_path("/Users/admin/Library/Developer/Xcode/DerivedData/AwardWallet-dsdmxwwnqdunwcabnxmtyaoqsqpu/")
test_without_building(true)
configuration("Release")
concurrent_simulators(true)
app_identifier("com.awardWallet.iphone")
# Arguments to pass to the app on launch. See https://docs.fastlane.tools/actions/snapshot/#launch-arguments
#launch_arguments(["-language de"])

# For more information about all available options run
# fastlane action snapshot
